### ISSUE TITLE
Organisms on Teaching server

### ISSUE THREAD

**Issue by jvanheld** [rsa-tools/rsat-code#20]
The Teaching Web server only displays a handful of organisms even though several thousands of genomes are available on the command line. 

This was a choice done earlier for didactic purposes. However it does not allow to use the phylogenetic tools. 

We should revise this policy and decide whether we want or not to support phylogenetic tools on the Teaching server. If yes, we need to enable either all the organisms, or to display an extended list of organisms.

**Comment by jvanheld** [comment]
The selection of organisms displayed on the Web server is defined in `rsat-code/perl-scripts/lib/RSAT/OrganismManager.pm`.

Here is the relevant chunk of code.

```{perl}
    } elsif ($group_specificity eq "Plants") {
      push @specific_taxa, "Viridiplantae";

    } elsif ($group_specificity eq "Teaching") {

      ## Define a list of model organisms                                                                                                                                                           
      my @model_organisms = qw(                                                                                                                                                                     
                             Arabidopsis_thaliana.TAIR10.29                                                                                                                                         
                             Bacillus_subtilis_168_uid57675                                                                                                                                         
                             Drosophila_melanogaster                                                                                                                                                
                             Escherichia_coli_GCF_000005845.2_ASM584v2                                                                                                                              
                             Homo_sapiens_GRCh37                                                                                                                                                    
                             Homo_sapiens_GRCh38                                                                                                                                                    
                             Mus_musculus_GRCm38                                                                                                                                                    
                             Saccharomyces_cerevisiae                                                                                                                                               
                            );

      ## Check that each organism is properly instaled.                                                                                                                                             
      foreach my $org (@model_organisms) {
        if ($main::supported_organism{$org}) {
          push @selected_organisms, $org
        }
      }
    } elsif ($group_specificity eq "None") {
      @selected_organisms = &get_supported_organisms();
```

**Comment by morganeTC** [comment]
Hi @jvanheld,

I think your analysis is wise : because the phylogenetic tools add a lot of organisms to the server, it makes the interest of having the teaching server less, and this does not help the novice user. 

If @amedina-liigh agrees, we could remove the phylogenetic tools from the Teaching server, and keep just the minimal organisms, which I think is OK is the chunk of code posted by @jvanheld

**Comment by morganeTC** [comment]
Hi @jvanheld,

My thinking is that these tools add a lot of organisms in the list to choose from, and the whole point of the teaching server is to provide less organisms for naive users. 

Maybe a way to meet would be to link the menu to either the Prokaryote or the Fungi server. It would be transparent for the user, would simplify the genomes maintenance (no need to maintain all these genomes on the teaching server), and limit the number of visible genomes for the novice users.

What do you think ?

**Comment by morganeTC** [comment]
Ha OK ! i did not realise this is the way it works (sorry). Then we can keep it like it used to be.

**Comment by jvanheld** [comment]
OK, I close this issue
