### ISSUE TITLE
default server used by "installer/06_install_organisms.bash" does not work

### ISSUE THREAD

**Issue by qisun2** [rsa-tools/rsat-code#36]
The default server used by "installer/06_install_organisms.bash" to download demo organism is "http://rsat-tagc.univ-mrs.fr/rsat/", it does not work.

**Comment by brunocontrerasmoreira** [comment]
Thanks for reporting it, can you use a different server?
@jvanheld should we restart/replcae that server?
Bruno

**Comment by qisun2** [comment]
I switched to "https://rsat.france-bioinformatique.fr/rsat/", then everything works.

**Comment by brunocontrerasmoreira** [comment]
Thanks for the tip, now fixed at https://github.com/rsa-tools/rsat-code/commit/b4b4eafd9da26af937bca72ff3791fc0b7fdc084
