### ISSUE TITLE
can't call get_attribute

### ISSUE THREAD

**Issue by Ajeet1699** [rsa-tools/rsat-code#4]
hi

When i am running peak-motifs, it gives me the following error:

`./rsat peak-motifs -i myreg.fna -ctrl gn.rm.fna -motif_db footDB transfac ~/packages/rsat/public_html/motif_databases/footprintDB/footprintDB.plants.motif.tf -prefix peaks -outdir outs -disco oligos,dyads -nmotifs 5 -minol 6 -maxol 8 -scan_markov 1 -noov -img_format png -task purge,seqlen,composition,disco,merge_motifs,split_motifs,timelog,motifs_vs_db,synthesis,small_summary,clean_seq`

"# sequence length: 29383, number of masked symbols: 2157 (7.34 percent of the sequences)"
"# sequence length: 138906, number of masked symbols: 9319 (6.71 percent of the sequences)"
; WARNING	Number of patterns = 118.	Exceeds top number = 100.	Only the top 100 patterns will be assembled.
Can't call method "get_attribute" on an undefined value at /home/mohini/packages/rsat/perl-scripts/lib/RSAT/MatrixAlignment.pm line 273.
Can't call method "get_attribute" on an undefined value at /home/mohini/packages/rsat/perl-scripts/lib/RSAT/MatrixAlignment.pm line 273.
Can't call method "get_attribute" on an undefined value at /home/mohini/packages/rsat/perl-scripts/lib/RSAT/MatrixAlignment.pm line 273.

**Comment by santanaw** [comment]
Hi Ajeet,

Many thanks for reporting this. 

1) Could you manually double-check that the file ~/packages/rsat/public_html/motif_databases/footprintDB/footprintDB.plants.motif.tf
contains relevant information?

2) In order to obtain a better insight of the problem, could you share the log file  of this peak-motif run? This would be inside your output directory: "outs/reports/*_log.txt

Best,

Walter

**Comment by Ajeet1699** [comment]
Thanks for the response. 
"contains relevant information" means availability of plant species? That is (Prunus persica) available in footprintDB.plants.motif.tf.

Please find attached both files
[peaks_log.txt](https://github.com/rsa-tools/rsat-code/files/6414704/peaks_log.txt)
[footprintDB.plants.motif.tf.txt](https://github.com/rsa-tools/rsat-code/files/6414706/footprintDB.plants.motif.tf.txt)

**Comment by santanaw** [comment]
Hi Ajeet,

Thanks for this information.

1) Regarding the footprintDB.plants.motif.tf file, I wanted  to make sure that it indeed contained information of motifs as the current issue so far seems to be linked to the comparison step between the discovered motifs ("outs/results/discovered_motifs/dyads_test_vs_ctrl_m4/peaks_dyads_test_vs_ctrl_m4.tf") and the motif database footprintDB.plants.motif.tf .

2) If convenient for you, can I have both input files "myreg.fna" and "gn.rm.fna" to reproduce the error? This can also be sent 
to the rsat-contact mail if needed to be shared privately. 

Best,

Walter

**Comment by Ajeet1699** [comment]
Dear Walter,
Thanks for your kind reply.
Please find attached "myreg.fna" and "gn.rm.fna" files.
Also I want to ask you if I can use peak-motifs for Chlamydomonas
reinhardtii? Can you suggest any
 gn.rm.fna
<https://drive.google.com/file/d/1cOjF63VGIsaAhbx2tzhy5xLTHP-JSHBr/view?usp=drive_web>
motif database for Chlamydomonas reinhardtii?

Thanks and regards

**Comment by santanaw** [comment]
Hi Ajeet,

Looking into this file file link, I noticed that it is only the "myreg.fna" file but the "gn.rm.fna" wasn't shared. 

It is indeed possible to use the installed genome of _Chlamydomonas reinhardtii_ in the [RSAT Plants server](http://rsat.eead.csic.es/plants/) for your peak-motifs analysis. In particular you can: (i) retrieve all the fasta interval sequences of interest from the _Chlamydomonas reinhardtii_  genome using [retrieve-seq-bed](http://rsat.eead.csic.es/plants/retrieve-seq-bed_form.cgi)  and (ii) input these sequences to peak-motifs to discover relevant motifs .

More information of available installed plants genomes can be found  at http://rsat.eead.csic.es/plants/supported-organisms.cgi . 

Regarding a motif database to use, the JASPAR plants collections could also be useful.

Kind regards

**Comment by brunocontrerasmoreira** [comment]
Hi, just adding that http://rsat.eead.csic.es/plants/motif_databases/footprintDB/footprintDB.plants.motif.tf is a non-redundant collection of plant motifs. It includes many from JASPAR, but also from other sources (see http://floresta.eead.csic.es/footprintdb/index.php),
Bruno

**Comment by Ajeet1699** [comment]
Hi Walter

Please find the attached
 gn.rm.fna
<https://drive.google.com/file/d/1IPVHswfNj7SV3DKD9nyhWiqFCocrRVGa/view?usp=drive_web>
"gn.rm.fna" file.

**Comment by santanaw** [comment]
Hi Ajeet,

Apologies, it was the opposite way. Could you please upload the "myreg.fna" file?

Thanks

**Comment by Ajeet1699** [comment]
Hi Walter.

Please find the attached file.
Thanks
